version: '3'
services:
  openproject:
    ports:
      - "${OP_PORT}:80"
    volumes:
      - ${OP_DB_DATA_DIR}:/var/lib/postgresql/9.4/main
      - ${OP_ATTACHMENTS_DIR}:/var/db/openproject
    environment:
      - SECRET_KEY_BASE
    image: openproject/community:7